# Am I doing this right? Almost certainly not. But the idea here is to store some of the repeated strings of text 
# (e.g., the boots are going to be largely the same for every uniform, so I'll put one string in here and reference it in every page, so that if I edit it I only need to edit it once)


